### ISSUE TITLE
Nur ein kleines Add-On

### ISSUE THREAD

**Issue by HSteindl** [Markus-Hanisch/Presentations#2]
Servus,

EINEN Tipp habe ich:
Bitte gib ENTWEDER eine Street-Address ODER die Geo-Coordinates an. Nach meiner Erfahrung passieren manchmal ganz eigenartige Dinge, wenn man beides als Metadaten für den Raum hinterlegt.  
In anderen Worten: GeoCoordinates nur dann, wenn Du z.B. ein großes Firmengelände hast und der BING Mapping-Dienst die Gebäude nicht verorten kann, weil alles unter "Siemensstrasse 1" läuft. ;-)

Bye
HST

**Comment by Markus-Hanisch** [comment]
@HSteindl 
Das PowerShell Script liegt doch bereits im Ordner?

**Comment by HSteindl** [comment]
Ähem, stimmt, sorry. Aus welchen Gründen auch immer, hab ich es im ersten Anlauf nicht gefunden. 
#brainfart 
DANKE!

**Comment by Markus-Hanisch** [comment]
No problemo 👌😁
